### ISSUE TITLE
Incorrect values on pressure

### ISSUE THREAD

**Issue by solarssk** [trekawek/air-quality-info#113]
Hi

I have today started feeding data from my weather station connected to Home Assistant.
The rest command looks as follows:

```yaml
rest_command:
  send_aqi_data:
    url: "https://api.aqi.eco/update/XXX"
    method: POST
    headers:
      Content-Type: application/json
    payload: >
      {
        "esp8266id": "XXXXXXXX",
        "software_version": "2024",
        "sensordatavalues": [
          {
            "value_type": "BME280_temperature",
            "value": "{{ states('sensor.loggia_esp01_temperature') }}"
          },
          {
            "value_type": "BME280_humidity",
            "value": "{{ states('sensor.loggia_esp01_humidity') }}"
          },
          {
            "value_type": "BME280_pressure",
            "value": "{{ states('sensor.loggia_esp01_pressure') }}"
          },          
          {
            "value_type": "SPS30_P1",
            "value": "{{ states('sensor.loggia_esp01_pm_1') }}"
          },
          {
            "value_type": "SPS30_P2",
            "value": "{{ states('sensor.loggia_esp01_pm_2_5') }}"
          },
          {
            "value_type": "SPS30_P4",
            "value": "{{ states('sensor.loggia_esp01_pm_4') }}"
          },
          {
            "value_type": "SPS30_P0",
            "value": "{{ states('sensor.loggia_esp01_pm_10') }}"
          },
          {
            "value_type": "SPS30_N05",
            "value": "{{ states('sensor.loggia_esp01_pmc_0_5') }}"
          },
          {
            "value_type": "SPS30_N1",
            "value": "{{ states('sensor.loggia_esp01_pmc_1') }}"
          },
          {
            "value_type": "SPS30_N25",
            "value": "{{ states('sensor.loggia_esp01_pmc_2_5') }}"
          },
          {
            "value_type": "SPS30_N4",
            "value": "{{ states('sensor.loggia_esp01_pmc_4') }}"
          },
          {
            "value_type": "SPS30_N10",
            "value": "{{ states('sensor.loggia_esp01_pmc_10') }}"
          },
          {
            "value_type": "ambient_light",
            "value": "{{ states('sensor.loggia_sensor_light_illuminance_lux') }}"
          }          
        ]
      }       
``` 

I can see that the values in the aqi.eco log are feeding correctly. 

`{ "esp8266id": "XXXXXXX", "software_version": "2024", "sensordatavalues": [ { "value_type": "BME280_temperature", "value": "15.1” }, { "value_type": "BME280_humidity", "value": "51.6” }, { "value_type": "BME280_pressure", "value": “1008” }, { "value_type": "SPS30_P1", "value": "1.34” }, { "value_type": "SPS30_P2", "value": “1.32" }, { "value_type": "SPS30_P4", "value": "1.42" }, { "value_type": "SPS30_P0", "value": "1.42" }, { "value_type": "SPS30_N05", "value": “10.51" }, { "value_type": "SPS30_N1", "value": "11.72" }, { "value_type": "SPS30_N25", "value": "11.73" }, { "value_type": "SPS30_N4", "value": "11.74" }, { "value_type": "SPS30_N10", "value": "11.74" }, { "value_type": "ambient_light", "value": "0" } ] }`

Unfortunately there is a problem with the atmospheric pressure. It presents itself as follows: `pressure 10,189432507511`

I've tried all sorts of combinations - I still get some value from space.

How can I help to verify the issue?

thx, Filip
